
name_or_path: /home/data/model/Mistral-7B-Instruct-v0.3
tokenizer_name_or_path: /home/data/model/Mistral-7B-Instruct-v0.3
archive: null
block_name: MistralDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: bfloat16
reference_dtype: bfloat16

resume_from_checkpoint_policy: False
resume_dir_policy: None

resume_from_checkpoint_ref: False
resume_dir_ref: None
