
name_or_path: /home/data/model/zephyr-7b-beta
tokenizer_name_or_path: /home/data/model/zephyr-7b-beta
archive: null
block_name: MistralDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: bfloat16
reference_dtype: bfloat16

resume_from_checkpoint_policy: False  # 是否从断点恢复训练
resume_dir_policy: None

resume_from_checkpoint_ref: False  # 是否从断点恢复训练
resume_dir_ref: None
