# 模型配置
name_or_path: /home/data/model/zephyr-7b-beta
tokenizer_name_or_path: /home/data/model/zephyr-7b-beta
archive: null
block_name: MistralDecoderLayer

resume_from_checkpoint_policy: False
resume_dir_policy: None

resume_from_checkpoint_ref: False 
resume_dir_ref: None

policy_dtype: bfloat16
fsdp_policy_mp: bfloat16
reference_dtype: bfloat16
