# do DPO preference-based training
name: dpo

# the temperature parameter for DPO
beta: 0.1

# the noise parameter for conservative DPO; should be in range (0, 0.5)
label_smoothing: 0

# if true, use a uniform (maximum entropy) reference model
reference_free: false

# λ
adaptive_lambda: 2.3026
